// Auto-generated code. Do not edit.
namespace myImages {

    helpers._registerFactory("image", function(name: string) {
        switch(helpers.stringTrim(name)) {
            case "QHdw2":
            case "Beaver0":return img`
............................................
............................................
............................................
...................eeeee....fff.............
...................effeeeeeeeeffeeefffee....
..................eeeefeeeeeeefefeeefffee...
..................effefeeeeeeeefefeefeefee..
..................efeefeeeeeeeefeefefeefee..
..................eefffeeeeeeeefeefefeefeee.
...................eeeeeeeeeeeeffeefeeefee..
....................eeeeeeeeeeefeeeeeefeeee.
......................eeeeeeeefeeeeeefeeee..
....................f......fffeeeeeeff......
.................ffffff.....feeeeeeeef......
..........ffffffffffffff.....feeefffeff.....
........ffeeeeeffeeeeeff......ffeffffff.....
.......feeeeefeeeeeefefff.....feffeeeeef....
....ffffeeeefeeeeefffeff......feeeeeeeef....
....ffeeeeefeeeeeeefeeeff.....feeeeeeef.....
....ffeeffeefeeeeeefeeefffff..feeeeeeef.....
ff..ffffeeffdffeeeeeeeeeeeffffeeeeeeeef.....
..ffffeeeeeefefeeeeeeeeeeeeeffffeeeeeef.....
ffffffeeefeefeefeeffeeeeffeeefffffeeeef.....
..ffffeefeeeefeeeeefeeeeefeeeeeefffeef......
..feefeeefeeeefeeeeeeeffeeeeeeeeeeffff......
..feeeeeeefeeeeeeeeeeeefeeeeeeeeeeefffff....
...feeeeefeeeeeeeeeeeeffeeeeeeeeeeeeefff....
....fefffffeeeeeffeeeeeeeeeeeefeeeeeeeffff..
.....fdfdf.fefeeefeefeeeeeeeeeeffeeeeeeffff.
.....ff.f..fefeeeeeefeeeeefeeeeffeeeeeeeffff
...........feefeeeeeffeeeeeeeeeeeeeeeeeeeeef
.....ff..f.feeefeeeeffeeeeeeeeeeeeeeeeeeeeee
.....fdffdfeeeffeeeeeeeeeeeeeeeeeeeeeeeeffee
.....fffffeeeeffeeeeeeeeeeeeeeeeeeeeeeeeeffe
......feeefffffffeeeeeeeeeeffeeeeeeefeeeffee
.......fff......ffeeeeeeeeeefeeeeeeeffeeeeee
.................ffeeeeefeeeeeeeeeeeffeeeeee
..................ffeeeffeeeeefefeeeeeeeeeee
...................ffeeeeeeeeeffffeeeeeeeeee
....................feeeeeeeeeeeeeeeeeeeeeee
`;
            case ")wP17v:M0`0_VWqd^`A!":
            case "Beaver1":return img`
............................................
.................eeeee....fff...............
.................effeeeeeeeeffeeefffee......
................eeeefeeeeeeefefeeefffee.....
................effefeeeeeeeefefeefeefee....
................efeefeeeeeeeefeefefeefee....
................eefffeeeeeeeefeefefeefeee...
.................eeeeeeeeeeeeffeefeeefee....
..................eeeeeeeeeeefeeeeeefeeee...
....................eeeeeeeefeeeeeefeeee....
.........................fffeeeeeeff........
..........................feeeeeeeef........
....................f......feeefffeff.......
.................ffffff.....ffeffffff.......
..........ffffffffffffff....feffeeeeef......
........ffeeeeeffeeeeeff....feeeeeeeef......
.......feeeeefeeeeeefefff...feeeeeeef.......
....ffffeeeefeeeeefffeff....feeeeeeef.......
....ffeeeeefeeeeeeefeeeff..feeeeeeeef.......
....ffeeffeefeeeeeefeeefffffeeeeeeeef.......
ff..ffffeeffdffeeeeeeeeeeefffeeeeeeef.......
..ffffeeeeeefefeeeeeeeeeeeeeffeeeeef........
ffffffeeefeefeefeeffeeeeffeeefffeeff........
..ffffeefeeeefeeeeefeeeeefeeeeeefff.........
..feefeeefeeeefeeeeeeeffeeeeeeeeeeffff......
..feeeeeeefeeeeeeeeeeeefeeeeeeeeeeefffff....
...feeeeefeeeeeeeeeeeeffeeeeeeeeeeeeefff....
....fefffffeeeeeffeeeeeeeeeeeefeeeeeeeffff..
.....fdfdf.fefeeefeefeeeeeeeeeeffeeeeeeffff.
.....ff.ff.feefeeeeefeeeeefeeeeffeeeeeeeffff
.....fdffdfeeefeeeeeffeeeeeeeeeeeeeeeeeeeeef
.....fffffeeeeffeeeeffeeeeeeeeeeeeeeeeeeeeee
......feeeffff.feeeeeeeeeeeeeeeeeeeeeeeeffee
.......fff.....feeeeeeeeeeeeeeeeeeeeeeeeeffe
...............ffeeeeeeeeeeffeeeeeeefeeeffee
................ffeeeeeeeeeefeeeeeeeffeeeeee
.................ffeeeeefeeeeeeeeeeeffeeeeee
..................ffeeeffeeeeefefeeeeeeeeeee
...................ffeeeeeeeeeffffeeeeeeeeee
....................feeeeeeeeeeeeeeeeeeeeeee
`;
            case "O)t#)gB!f{CC~er{HBmu":
            case "Beaver2":return img`
...............eeeee....fff.................
...............effeeeeeeeeffeeefffee........
..............eeeefeeeeeeefefeeefffee.......
..............effefeeeeeeeefefeefeefee......
..............efeefeeeeeeeefeefefeefee......
..............eefffeeeeeeeefeefefeefeee.....
...............eeeeeeeeeeeeffeefeeefee......
................eeeeeeeeeeefeeeeeefeeee.....
..................eeeeeeeefeeeeeefeeee......
.......................fffeeeeeeff..........
........................feeeeeeeef..........
.........................feeefffeff.........
....................f.....ffeffffff.........
.................ffffff...feffeeeeef........
..........ffffffffffffff..feeeeeeeef........
........ffeeeeeffeeeeeff..feeeeeeef.........
.......feeeeefeeeeeefefff.feeeeeeef.........
....ffffeeeefeeeeefffeff..feeeeeeef.........
....ffeeeeefeeeeeeefeeeff.feeeeeeef.........
....ffeeffeefeeeeeefeeefffffeeeeeef.........
ff..ffffeeffdffeeeeeeeeeeeffffeeef..........
..ffffeeeeeefefeeeeeeeeeeeeeffffef..........
ffffffeeefeefeefeeffeeeeffeeefffff..........
..ffffeefeeeefeeeeefeeeeefeeeeeefff.........
..feefeeefeeeefeeeeeeeffeeeeeeeeeeffff......
..feeeeeeefeeeeeeeeeeeefeeeeeeeeeeefffff....
...feeeeefeeeeeeeeeeeeffeeeeeeeeeeeeefff....
....fffffffeeeeeffeeeeeeeeeeeefeeeeeeeffff..
....fdffdfeeefeeefeefeeeeeeeeeeffeeeeeeffff.
.....ffffeeeeffeeeeefeeeeefeeeeffeeeeeeeffff
.....feeeffff.feeeeeffeeeeeeeeeeeeeeeeeeeeef
......fff.....ffeeeeffeeeeeeeeeeeeeeeeeeeeee
...............feeeeeeeeeeeeeeeeeeeeeeeeffee
...............feeeeeeeeeeeeeeeeeeeeeeeeeffe
...............ffeeeeeeeeeeffeeeeeeefeeeffee
................ffeeeeeeeeeefeeeeeeeffeeeeee
.................ffeeeeefeeeeeeeeeeeffeeeeee
..................ffeeeffeeeeefefeeeeeeeeeee
...................ffeeeeeeeeeffffeeeeeeeeee
....................feeeeeeeeeeeeeeeeeeeeeee
`;
            case "jYkD|CGKG6/@Okb-!~SX":
            case "Beaver3":return img`
............................................
.................eeeee....fff...............
.................effeeeeeeeeffeeefffee......
................eeeefeeeeeeefefeeefffee.....
................effefeeeeeeeefefeefeefee....
................efeefeeeeeeeefeefefeefee....
................eefffeeeeeeeefeefefeefeee...
.................eeeeeeeeeeeeffeefeeefee....
..................eeeeeeeeeeefeeeeeefeeee...
....................eeeeeeeefeeeeeefeeee....
.........................fffeeeeeeff........
..........................feeeeeeeef........
....................f......feeefffeff.......
.................ffffff.....ffeffffff.......
..........ffffffffffffff....feffeeeeef......
........ffeeeeeffeeeeeff....feeeeeeeef......
.......feeeeefeeeeeefefff...feeeeeeef.......
....ffffeeeefeeeeefffeff....feeeeeeef.......
....ffeeeeefeeeeeeefeeeff..feeeeeeeef.......
....ffeeffeefeeeeeefeeefffffeeeeeeeef.......
ff..ffffeefffffeeeeeeeeeeefffeeeeeeef.......
..ffffeeeeeefefeeeeeeeeeeeeeffeeeeef........
ffffffeeefeefeefeeffeeeeffeeefffeeff........
..ffffeefeeeefeeeeefeeeeefeeeeeefff.........
..feefeeefeeeefeeeeeeeffeeeeeeeeeeffff......
..feeeeeeefeeeeeeeeeeeefeeeeeeeeeeefffff....
...feeeeefeeeeeeeeeeeeffeeeeeeeeeeeeefff....
....fefffffeeeeeffeeeeeeeeeeeefeeeeeeeffff..
.....fdfdf.fefeeefeefeeeeeeeeeeffeeeeeeffff.
.....ff.ff.feefeeeeefeeeeefeeeeffeeeeeeeffff
.....fdffdfeeefeeeeeffeeeeeeeeeeeeeeeeeeeeef
.....fffffeeeeffeeeeffeeeeeeeeeeeeeeeeeeeeee
......feeeffff.feeeeeeeeeeeeeeeeeeeeeeeeffee
.......fff.....feeeeeeeeeeeeeeeeeeeeeeeeeffe
...............ffeeeeeeeeeeffeeeeeeefeeeffee
................ffeeeeeeeeeefeeeeeeeffeeeeee
.................ffeeeeefeeeeeeeeeeeffeeeeee
..................ffeeeffeeeeefefeeeeeeeeeee
...................ffeeeeeeeeeffffeeeeeeeeee
....................feeeeeeeeeeeeeeeeeeeeeee
`;
        }
        return null;
    })

    helpers._registerFactory("animation", function(name: string) {
        switch(helpers.stringTrim(name)) {

        }
        return null;
    })

}
// Auto-generated code. Do not edit.
