// Auto-generated code. Do not edit.
namespace myImages {

    helpers._registerFactory("image", function(name: string) {
        switch(helpers.stringTrim(name)) {
            case "image1":
            case "heroWalkFront2":return img`
. . . . . . . . . . . . . . . . 
. . . . . . f f f f . . . . . . 
. . . . f f f 2 2 f f f . . . . 
. . . f f f 2 2 2 2 f f f . . . 
. . f f f e e e e e e f f f . . 
. . f f e 2 2 2 2 2 2 e e f . . 
. f f e 2 f f f f f f 2 e f f . 
. f f f f f e e e e f f f f f . 
. . f e f b f 4 4 f b f e f . . 
. . f e 4 1 f d d f 1 4 e f . . 
. . . f e 4 d d d d 4 e f e . . 
. . f e f 2 2 2 2 e d d 4 e . . 
. . e 4 f 2 2 2 2 e d d e . . . 
. . . . f 4 4 5 5 f e e . . . . 
. . . . f f f f f f f . . . . . 
. . . . f f f . . . . . . . . . 
`;
            case "image2":
            case "tree":return img`
................86..................
...........6688867886...............
...........8666877688868............
............868777767768............
.........688667777776688............
........67767777777778666...........
.........6776667767666868...........
..........866667667677688...........
.........8666666666667778...........
........667766666666666676..........
.......67766667666776667776.........
......886667776676777666688.........
.....67766777667767777666768........
....6776666666777667776666776.......
.....8667776667766676677776776......
......8777666666667776777776688.....
....6887766776677677777777776776....
..8866666677767777777777766666778...
.86666666777667767777766666776668...
..88677666666777677677666667776668..
..86776677666666666666667776666668..
886666677766667666666776677766668...
6668666676667766767767766677666668..
88866666666777677677667666666776668.
.86668866666766776776666667766666668
.86688666666666776666667667776666688
.668866666666666666666677666666688..
..8866686666666666677667776666668...
...866886666666666677667776666668...
...86886668666666667666666666888....
....88866886686666666666666668......
......86886668666866668666868.......
......88866688668866688866888.......
........8888888688888ce868..........
..............e88e88.ec.8...........
...............eeee..e..............
...............ceef.ce..............
...............ceefcec..............
...............feefce...............
...............fceeec...............
...............ffceec...............
`;
            case "image3":
            case "a":return img`
.............fff....eeeee...................
....eefffeeeffeeeeeeeeffe...................
...eefffeeefefeeeeeeefeeee..................
..eefeefeefefeeeeeeeefeffe..................
..eefeefefeefeeeeeeeefeefe..................
.eeefeefefeefeeeeeeeefffee..................
..eefeeefeeffeeeeeeeeeeee...................
.eeeefeeeeeefeeeeeeeeeee....................
..eeeefeeeeeefeeeeeeee......................
......ffeeeeeefff......f....................
......feeeeeeeef.....ffffff.................
.....ffefffeeef.....ffffffffffffff..........
.....ffffffeff......ffeeeeeffeeeeeff........
....feeeeeffef.....fffefeeeeeefeeeeef.......
....feeeeeeeef......ffefffeeeeefeeeeffff....
.....feeeeeeef.....ffeeefeeeeeeefeeeeeff....
.....feeeeeeef..fffffeeefeeeeeefeeffeeff....
.....feeeeeeeeffffeeeeeeeeeeeffdffeeffff..ff
.....feeeeeeffffeeeeeeeeeeeeefefeeeeeeffff..
.....feeeefffffeeeffeeeeffeefeefeefeeeffffff
......feefffeeeeeefeeeeefeeeeefeeeefeeffff..
......ffffeeeeeeeeeeffeeeeeeefeeeefeeefeef..
....fffffeeeeeeeeeeefeeeeeeeeeeeefeeeeeeef..
....fffeeeeeeeeeeeeeffeeeeeeeeeeeefeeeeef...
..ffffeeeeeeefeeeeeeeeeeeeffeeeeefffffef....
.ffffeeeeeeffeeeeeeeeeefeefeeefef.fdfdf.....
ffffeeeeeeeffeeeefeeeeefeeeeeefef..f.ff.....
feeeeeeeeeeeeeeeeeeeeeffeeeeefeef...........
eeeeeeeeeeeeeeeeeeeeeeffeeeefeeef.f..ff.....
eeffeeeeeeeeeeeeeeeeeeeeeeeeffeeefdffdf.....
effeeeeeeeeeeeeeeeeeeeeeeeeeffeeeefffff.....
eeffeeefeeeeeeeffeeeeeeeeeefffffffeeef......
eeeeeeffeeeeeeefeeeeeeeeeeff......fff.......
eeeeeeffeeeeeeeeeeefeeeeeff.................
eeeeeeeeeeefefeeeeeffeeeff..................
eeeeeeeeeeffffeeeeeeeeeff...................
eeeeeeeeeeeeeeeeeeeeeeef....................
`;
            case "image4":
            case "b":return img`
.....eefffeeefefeeeeeeefeeee................
....eefeefeefefeeeeeeeefeffe................
....eefeefefeefeeeeeeeefeefe................
...eeefeefefeefeeeeeeeefffee................
....eefeeefeeffeeeeeeeeeeee.................
...eeeefeeeeeefeeeeeeeeeee..................
....eeeefeeeeeefeeeeeeee....................
........ffeeeeeefff.........................
........feeeeeeeef..........................
.......ffefffeeef......f....................
.......ffffffeff.....ffffff.................
......feeeeeffef....ffffffffffffff..........
......feeeeeeeef....ffeeeeeffeeeeeff........
.......feeeeeeef...fffefeeeeeefeeeeef.......
.......feeeeeeef....ffefffeeeeefeeeeffff....
.......feeeeeeeef..ffeeefeeeeeeefeeeeeff....
.......feeeeeeeefffffeeefeeeeeefeeffeeff....
.......feeeeeeefffeeeeeeeeeeeffdffeeffff..ff
........feeeeeffeeeeeeeeeeeeefefeeeeeeffff..
........ffeefffeeeffeeeeffeefeefeefeeeffffff
.........fffeeeeeefeeeeefeeeeefeeeefeeffff..
......ffffeeeeeeeeeeffeeeeeeefeeeefeeefeef..
....fffffeeeeeeeeeeefeeeeeeeeeeeefeeeeeeef..
....fffeeeeeeeeeeeeeffeeeeeeeeeeeefeeeeef...
..ffffeeeeeeefeeeeeeeeeeeeffeeeeefffffef....
.ffffeeeeeeffeeeeeeeeeefeefeeefef.fdfdf.....
ffffeeeeeeeffeeeefeeeeefeeeeefeef.ff.ff.....
feeeeeeeeeeeeeeeeeeeeeffeeeeefeeefdffdf.....
eeeeeeeeeeeeeeeeeeeeeeffeeeeffeeeefffff.....
eeffeeeeeeeeeeeeeeeeeeeeeeeef.ffffeeef......
effeeeeeeeeeeeeeeeeeeeeeeeeef.....fff.......
eeffeeefeeeeeeeffeeeeeeeeeeff...............
eeeeeeffeeeeeeefeeeeeeeeeeff................
eeeeeeffeeeeeeeeeeefeeeeeff.................
eeeeeeeeeeefefeeeeeffeeeff..................
eeeeeeeeeeffffeeeeeeeeeff...................
eeeeeeeeeeeeeeeeeeeeeeef....................
`;
            case "image5":
            case "c":return img`
......eefeefeefefeeeeeeeefeffe..............
......eefeefefeefeeeeeeeefeefe..............
.....eeefeefefeefeeeeeeeefffee..............
......eefeeefeeffeeeeeeeeeeee...............
.....eeeefeeeeeefeeeeeeeeeee................
......eeeefeeeeeefeeeeeeee..................
..........ffeeeeeefff.......................
..........feeeeeeeef........................
.........ffefffeeef.........................
.........ffffffeff.....f....................
........feeeeeffef...ffffff.................
........feeeeeeeef..ffffffffffffff..........
.........feeeeeeef..ffeeeeeffeeeeeff........
.........feeeeeeef.fffefeeeeeefeeeeef.......
.........feeeeeeef..ffefffeeeeefeeeeffff....
.........feeeeeeef.ffeeefeeeeeeefeeeeeff....
.........feeeeeefffffeeefeeeeeefeeffeeff....
..........feeeffffeeeeeeeeeeeffdffeeffff..ff
..........feffffeeeeeeeeeeeeefefeeeeeeffff..
..........fffffeeeffeeeeffeefeefeefeeeffffff
.........fffeeeeeefeeeeefeeeeefeeeefeeffff..
......ffffeeeeeeeeeeffeeeeeeefeeeefeeefeef..
....fffffeeeeeeeeeeefeeeeeeeeeeeefeeeeeeef..
....fffeeeeeeeeeeeeeffeeeeeeeeeeeefeeeeef...
..ffffeeeeeeefeeeeeeeeeeeeffeeeeefffffff....
.ffffeeeeeeffeeeeeeeeeefeefeeefeeefdffdf....
ffffeeeeeeeffeeeefeeeeefeeeeeffeeeeffff.....
feeeeeeeeeeeeeeeeeeeeeffeeeeef.ffffeeef.....
eeeeeeeeeeeeeeeeeeeeeeffeeeeff.....fff......
eeffeeeeeeeeeeeeeeeeeeeeeeeef...............
effeeeeeeeeeeeeeeeeeeeeeeeeef...............
eeffeeefeeeeeeeffeeeeeeeeeeff...............
eeeeeeffeeeeeeefeeeeeeeeeeff................
eeeeeeffeeeeeeeeeeefeeeeeff.................
eeeeeeeeeeefefeeeeeffeeeff..................
eeeeeeeeeeffffeeeeeeeeeff...................
eeeeeeeeeeeeeeeeeeeeeeef....................
`;
            case "image6":
            case "d":return img`
.....eefffeeefefeeeeeeefeeee................
....eefeefeefefeeeeeeeefeffe................
....eefeefefeefeeeeeeeefeefe................
...eeefeefefeefeeeeeeeefffee................
....eefeeefeeffeeeeeeeeeeee.................
...eeeefeeeeeefeeeeeeeeeee..................
....eeeefeeeeeefeeeeeeee....................
........ffeeeeeefff.........................
........feeeeeeeef..........................
.......ffefffeeef......f....................
.......ffffffeff.....ffffff.................
......feeeeeffef....ffffffffffffff..........
......feeeeeeeef....ffeeeeeffeeeeeff........
.......feeeeeeef...fffefeeeeeefeeeeef.......
.......feeeeeeef....ffefffeeeeefeeeeffff....
.......feeeeeeeef..ffeeefeeeeeeefeeeeeff....
.......feeeeeeeefffffeeefeeeeeefeeffeeff....
.......feeeeeeefffeeeeeeeeeeeffdffeeffff..ff
........feeeeeffeeeeeeeeeeeeefefeeeeeeffff..
........ffeefffeeeffeeeeffeefeefeefeeeffffff
.........fffeeeeeefeeeeefeeeeefeeeefeeffff..
......ffffeeeeeeeeeeffeeeeeeefeeeefeeefeef..
....fffffeeeeeeeeeeefeeeeeeeeeeeefeeeeeeef..
....fffeeeeeeeeeeeeeffeeeeeeeeeeeefeeeeef...
..ffffeeeeeeefeeeeeeeeeeeeffeeeeefffffef....
.ffffeeeeeeffeeeeeeeeeefeefeeefef.fdfdf.....
ffffeeeeeeeffeeeefeeeeefeeeeefeef.ff.ff.....
feeeeeeeeeeeeeeeeeeeeeffeeeeefeeefdffdf.....
eeeeeeeeeeeeeeeeeeeeeeffeeeeffeeeefffff.....
eeffeeeeeeeeeeeeeeeeeeeeeeeef.ffffeeef......
effeeeeeeeeeeeeeeeeeeeeeeeeef.....fff.......
eeffeeefeeeeeeeffeeeeeeeeeeff...............
eeeeeeffeeeeeeefeeeeeeeeeeff................
eeeeeeffeeeeeeeeeeefeeeeeff.................
eeeeeeeeeeefefeeeeeffeeeff..................
eeeeeeeeeeffffeeeeeeeeeff...................
eeeeeeeeeeeeeeeeeeeeeeef....................
`;
        }
        return null;
    })

    helpers._registerFactory("animation", function(name: string) {
        switch(helpers.stringTrim(name)) {

        }
        return null;
    })

}
// Auto-generated code. Do not edit.
