function cow () {
    cow_0 = assets.image`cow0`
    cow_1 = assets.image`cow1`
    cow_2 = assets.image`cow2`
    cow_3 = assets.image`cow3`
}
function beaver () {
    Beaver2_0_0 = img`
        ............................................
        ............................................
        ............................................
        ...................eeeee....fff.............
        ...................effeeeeeeeeffeeefffee....
        ..................eeeefeeeeeeefefeeefffee...
        ..................effefeeeeeeeefefeefeefee..
        ..................efeefeeeeeeeefeefefeefee..
        ..................eefffeeeeeeeefeefefeefeee.
        ...................eeeeeeeeeeeeffeefeeefee..
        ....................eeeeeeeeeeefeeeeeefeeee.
        ......................eeeeeeeefeeeeeefeeee..
        ....................f......fffeeeeeeff......
        .................ffffff.....feeeeeeeef......
        ..........ffffffffffffff.....feeefffeff.....
        ........ffeeeeeffeeeeeff......ffeffffff.....
        .......feeeeefeeeeeefefff.....feffeeeeef....
        ....ffffeeeefeeeeefffeff......feeeeeeeef....
        ....ffeeeeefeeeeeeefeeeff.....feeeeeeef.....
        ....ffeeffeefeeeeeefeeefffff..feeeeeeef.....
        ff..ffffeeffdffeeeeeeeeeeeffffeeeeeeeef.....
        ..ffffeeeeeefefeeeeeeeeeeeeeffffeeeeeef.....
        ffffffeeefeefeefeeffeeeeffeeefffffeeeef.....
        ..ffffeefeeeefeeeeefeeeeefeeeeeefffeef......
        ..feefeeefeeeefeeeeeeeffeeeeeeeeeeffff......
        ..feeeeeeefeeeeeeeeeeeefeeeeeeeeeeefffff....
        ...feeeeefeeeeeeeeeeeeffeeeeeeeeeeeeefff....
        ....fefffffeeeeeffeeeeeeeeeeeefeeeeeeeffff..
        .....fdfdf.fefeeefeefeeeeeeeeeeffeeeeeeffff.
        .....ff.f..fefeeeeeefeeeeefeeeeffeeeeeeeffff
        ...........feefeeeeeffeeeeeeeeeeeeeeeeeeeeef
        .....ff..f.feeefeeeeffeeeeeeeeeeeeeeeeeeeeee
        .....fdffdfeeeffeeeeeeeeeeeeeeeeeeeeeeeeffee
        .....fffffeeeeffeeeeeeeeeeeeeeeeeeeeeeeeeffe
        ......feeefffffffeeeeeeeeeeffeeeeeeefeeeffee
        .......fff......ffeeeeeeeeeefeeeeeeeffeeeeee
        .................ffeeeeefeeeeeeeeeeeffeeeeee
        ..................ffeeeffeeeeefefeeeeeeeeeee
        ...................ffeeeeeeeeeffffeeeeeeeeee
        ....................feeeeeeeeeeeeeeeeeeeeeee
        `
    Beaver2_0_1 = img`
        ............................................
        .................eeeee....fff...............
        .................effeeeeeeeeffeeefffee......
        ................eeeefeeeeeeefefeeefffee.....
        ................effefeeeeeeeefefeefeefee....
        ................efeefeeeeeeeefeefefeefee....
        ................eefffeeeeeeeefeefefeefeee...
        .................eeeeeeeeeeeeffeefeeefee....
        ..................eeeeeeeeeeefeeeeeefeeee...
        ....................eeeeeeeefeeeeeefeeee....
        .........................fffeeeeeeff........
        ..........................feeeeeeeef........
        ....................f......feeefffeff.......
        .................ffffff.....ffeffffff.......
        ..........ffffffffffffff....feffeeeeef......
        ........ffeeeeeffeeeeeff....feeeeeeeef......
        .......feeeeefeeeeeefefff...feeeeeeef.......
        ....ffffeeeefeeeeefffeff....feeeeeeef.......
        ....ffeeeeefeeeeeeefeeeff..feeeeeeeef.......
        ....ffeeffeefeeeeeefeeefffffeeeeeeeef.......
        ff..ffffeeffdffeeeeeeeeeeefffeeeeeeef.......
        ..ffffeeeeeefefeeeeeeeeeeeeeffeeeeef........
        ffffffeeefeefeefeeffeeeeffeeefffeeff........
        ..ffffeefeeeefeeeeefeeeeefeeeeeefff.........
        ..feefeeefeeeefeeeeeeeffeeeeeeeeeeffff......
        ..feeeeeeefeeeeeeeeeeeefeeeeeeeeeeefffff....
        ...feeeeefeeeeeeeeeeeeffeeeeeeeeeeeeefff....
        ....fefffffeeeeeffeeeeeeeeeeeefeeeeeeeffff..
        .....fdfdf.fefeeefeefeeeeeeeeeeffeeeeeeffff.
        .....ff.ff.feefeeeeefeeeeefeeeeffeeeeeeeffff
        .....fdffdfeeefeeeeeffeeeeeeeeeeeeeeeeeeeeef
        .....fffffeeeeffeeeeffeeeeeeeeeeeeeeeeeeeeee
        ......feeeffff.feeeeeeeeeeeeeeeeeeeeeeeeffee
        .......fff.....feeeeeeeeeeeeeeeeeeeeeeeeeffe
        ...............ffeeeeeeeeeeffeeeeeeefeeeffee
        ................ffeeeeeeeeeefeeeeeeeffeeeeee
        .................ffeeeeefeeeeeeeeeeeffeeeeee
        ..................ffeeeffeeeeefefeeeeeeeeeee
        ...................ffeeeeeeeeeffffeeeeeeeeee
        ....................feeeeeeeeeeeeeeeeeeeeeee
        `
    Beaver2_0_2 = img`
        ...............eeeee....fff.................
        ...............effeeeeeeeeffeeefffee........
        ..............eeeefeeeeeeefefeeefffee.......
        ..............effefeeeeeeeefefeefeefee......
        ..............efeefeeeeeeeefeefefeefee......
        ..............eefffeeeeeeeefeefefeefeee.....
        ...............eeeeeeeeeeeeffeefeeefee......
        ................eeeeeeeeeeefeeeeeefeeee.....
        ..................eeeeeeeefeeeeeefeeee......
        .......................fffeeeeeeff..........
        ........................feeeeeeeef..........
        .........................feeefffeff.........
        ....................f.....ffeffffff.........
        .................ffffff...feffeeeeef........
        ..........ffffffffffffff..feeeeeeeef........
        ........ffeeeeeffeeeeeff..feeeeeeef.........
        .......feeeeefeeeeeefefff.feeeeeeef.........
        ....ffffeeeefeeeeefffeff..feeeeeeef.........
        ....ffeeeeefeeeeeeefeeeff.feeeeeeef.........
        ....ffeeffeefeeeeeefeeefffffeeeeeef.........
        ff..ffffeeffdffeeeeeeeeeeeffffeeef..........
        ..ffffeeeeeefefeeeeeeeeeeeeeffffef..........
        ffffffeeefeefeefeeffeeeeffeeefffff..........
        ..ffffeefeeeefeeeeefeeeeefeeeeeefff.........
        ..feefeeefeeeefeeeeeeeffeeeeeeeeeeffff......
        ..feeeeeeefeeeeeeeeeeeefeeeeeeeeeeefffff....
        ...feeeeefeeeeeeeeeeeeffeeeeeeeeeeeeefff....
        ....fffffffeeeeeffeeeeeeeeeeeefeeeeeeeffff..
        ....fdffdfeeefeeefeefeeeeeeeeeeffeeeeeeffff.
        .....ffffeeeeffeeeeefeeeeefeeeeffeeeeeeeffff
        .....feeeffff.feeeeeffeeeeeeeeeeeeeeeeeeeeef
        ......fff.....ffeeeeffeeeeeeeeeeeeeeeeeeeeee
        ...............feeeeeeeeeeeeeeeeeeeeeeeeffee
        ...............feeeeeeeeeeeeeeeeeeeeeeeeeffe
        ...............ffeeeeeeeeeeffeeeeeeefeeeffee
        ................ffeeeeeeeeeefeeeeeeeffeeeeee
        .................ffeeeeefeeeeeeeeeeeffeeeeee
        ..................ffeeeffeeeeefefeeeeeeeeeee
        ...................ffeeeeeeeeeffffeeeeeeeeee
        ....................feeeeeeeeeeeeeeeeeeeeeee
        `
    Beaver2_0_3 = img`
        ............................................
        .................eeeee....fff...............
        .................effeeeeeeeeffeeefffee......
        ................eeeefeeeeeeefefeeefffee.....
        ................effefeeeeeeeefefeefeefee....
        ................efeefeeeeeeeefeefefeefee....
        ................eefffeeeeeeeefeefefeefeee...
        .................eeeeeeeeeeeeffeefeeefee....
        ..................eeeeeeeeeeefeeeeeefeeee...
        ....................eeeeeeeefeeeeeefeeee....
        .........................fffeeeeeeff........
        ..........................feeeeeeeef........
        ....................f......feeefffeff.......
        .................ffffff.....ffeffffff.......
        ..........ffffffffffffff....feffeeeeef......
        ........ffeeeeeffeeeeeff....feeeeeeeef......
        .......feeeeefeeeeeefefff...feeeeeeef.......
        ....ffffeeeefeeeeefffeff....feeeeeeef.......
        ....ffeeeeefeeeeeeefeeeff..feeeeeeeef.......
        ....ffeeffeefeeeeeefeeefffffeeeeeeeef.......
        ff..ffffeefffffeeeeeeeeeeefffeeeeeeef.......
        ..ffffeeeeeefefeeeeeeeeeeeeeffeeeeef........
        ffffffeeefeefeefeeffeeeeffeeefffeeff........
        ..ffffeefeeeefeeeeefeeeeefeeeeeefff.........
        ..feefeeefeeeefeeeeeeeffeeeeeeeeeeffff......
        ..feeeeeeefeeeeeeeeeeeefeeeeeeeeeeefffff....
        ...feeeeefeeeeeeeeeeeeffeeeeeeeeeeeeefff....
        ....fefffffeeeeeffeeeeeeeeeeeefeeeeeeeffff..
        .....fdfdf.fefeeefeefeeeeeeeeeeffeeeeeeffff.
        .....ff.ff.feefeeeeefeeeeefeeeeffeeeeeeeffff
        .....fdffdfeeefeeeeeffeeeeeeeeeeeeeeeeeeeeef
        .....fffffeeeeffeeeeffeeeeeeeeeeeeeeeeeeeeee
        ......feeeffff.feeeeeeeeeeeeeeeeeeeeeeeeffee
        .......fff.....feeeeeeeeeeeeeeeeeeeeeeeeeffe
        ...............ffeeeeeeeeeeffeeeeeeefeeeffee
        ................ffeeeeeeeeeefeeeeeeeffeeeeee
        .................ffeeeeefeeeeeeeeeeeffeeeeee
        ..................ffeeeffeeeeefefeeeeeeeeeee
        ...................ffeeeeeeeeeffffeeeeeeeeee
        ....................feeeeeeeeeeeeeeeeeeeeeee
        `
}
let Beaver2_0_3: Image = null
let Beaver2_0_2: Image = null
let Beaver2_0_1: Image = null
let Beaver2_0_0: Image = null
let cow_3: Image = null
let cow_2: Image = null
let cow_1: Image = null
let cow_0: Image = null
beaver()
cow()
